import { defineCommand } from 'citty'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'pathe'
import yaml from 'yaml'
import openapiTS, { astToString } from 'openapi-typescript'
import type { OpenAPI3 } from 'openapi-typescript'
import { loadStack } from '../../core/stack-loader.js'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const NO_OVERRIDE = '// openapi-no-override'

const banner = `\
// This file is auto-generated by \`dude api sync\`.
// Manual changes will be overwritten on the next run.
// To keep your edits, add \`// openapi-no-override\` as the very first line.
`

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function shouldWrite(filePath: string): boolean {
  if (!existsSync(filePath)) return true
  const first = readFileSync(filePath, 'utf8').split('\n')[0] ?? ''
  return !first.startsWith(NO_OVERRIDE)
}

function safeWrite(filePath: string, content: string): boolean {
  if (!shouldWrite(filePath)) return false
  mkdirSync(path.dirname(filePath), { recursive: true })
  writeFileSync(filePath, content, 'utf8')
  return true
}

/** `/api/todos/{id}/` → `['api', 'todos', '[id]']` */
function routeToSegments(route: string): string[] {
  return route.split('/').filter(Boolean).map((s) => s.replace(/{(.+?)}/g, '[$1]'))
}

function cap(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

/** Relative import from a route folder at `depth` levels to the shared utils. */
function toUtils(depth: number) {
  return '../'.repeat(depth) + 'utils/openapi.types'
}

// ---------------------------------------------------------------------------
// Code generators
// ---------------------------------------------------------------------------

type Methods = Record<string, any>

function generateTypesFile(route: string, methods: Methods, depth: number): string {
  const imports = new Set<string>()
  let body = ''

  for (const [method, details] of Object.entries(methods)) {
    const M = cap(method)
    body += `// ${method.toUpperCase()}\n`

    // Query parameters
    if (details.parameters?.some((p: any) => p.in === 'query')) {
      imports.add('paths')
      body += `export type ${M}Parameters = paths['${route}']['${method}']['parameters']['query']\n`
    }

    // Request body
    if (details.requestBody?.content) {
      const content = details.requestBody.content
      const schema =
        content['application/json']?.schema ??
        content['multipart/form-data']?.schema ??
        content['application/x-www-form-urlencoded']?.schema
      if (schema?.$ref) {
        const name = (schema.$ref as string).split('/').pop()
        imports.add('components')
        body += `export type ${M}RequestBody = components['schemas']['${name}']\n`
      } else {
        body += `export type ${M}RequestBody = unknown\n`
      }
    }

    // Response
    const firstCode = details.responses ? Object.keys(details.responses)[0] : undefined
    const responseContent = firstCode ? details.responses[firstCode]?.content : undefined
    if (responseContent) {
      const schema = responseContent['application/json']?.schema
      if (schema?.$ref) {
        const name = (schema.$ref as string).split('/').pop()
        imports.add('components')
        body += `export type ${M}Response = components['schemas']['${name}']\n`
      } else if (schema?.type === 'array' && schema.items?.$ref) {
        const name = (schema.items.$ref as string).split('/').pop()
        imports.add('components')
        body += `export type ${M}Response = components['schemas']['${name}'][]\n`
      } else {
        body += `export type ${M}Response = unknown\n`
      }
    } else {
      body += `export type ${M}Response = void\n`
    }

    body += '\n'
  }

  let out = banner
  if (imports.size > 0) {
    out += `import type { ${[...imports].join(', ')} } from '${toUtils(depth)}'\n\n`
  }
  return out + body
}

function generateIndexFile(route: string, methods: Methods): string {
  const pathParams = (route.match(/{(.+?)}/g) ?? []).map((m) => m.slice(1, -1))
  const importedTypes = new Set<string>()
  let body = ''

  for (const [method, details] of Object.entries(methods)) {
    const M = cap(method)
    const args: string[] = []

    if (pathParams.length > 0) args.push(pathParams.map((p) => `${p}: string`).join(', '))

    const hasQuery = details.parameters?.some((p: any) => p.in === 'query') ?? false
    const hasBody = !!details.requestBody

    if (hasQuery) {
      args.push(`params: ${M}Parameters`)
      importedTypes.add(`${M}Parameters`)
    }
    if (hasBody) {
      args.push(`body: ${M}RequestBody`)
      importedTypes.add(`${M}RequestBody`)
    }
    importedTypes.add(`${M}Response`)

    // URL expression — template literal when path params are present
    const urlExpr =
      pathParams.length > 0
        ? `\`${route.replace(/{(.+?)}/g, (_, p) => `\${${p}}`)}\``
        : `'${route}'`

    // Fetch options
    const fetchOpts: string[] = []
    if (method !== 'get') fetchOpts.push(`method: '${method.toUpperCase()}'`)
    if (hasBody) {
      fetchOpts.push(`headers: { 'Content-Type': 'application/json' }`)
      fetchOpts.push(`body: JSON.stringify(body)`)
    }
    const optsStr = fetchOpts.length > 0 ? `, { ${fetchOpts.join(', ')} }` : ''

    // URL string — append query string for GET with params
    const urlStr = hasQuery ? `uri + '?' + new URLSearchParams(params as Record<string, string>)` : `uri`

    body += `export const $${method} = (${args.join(', ')}): Promise<${M}Response> => {\n`
    body += `  const uri = ${urlExpr}\n`
    body += `  return fetch(${urlStr}${optsStr}).then(r => r.json() as Promise<${M}Response>)\n`
    body += `}\n\n`
  }

  let out = banner
  if (importedTypes.size > 0) {
    out += `import type { ${[...importedTypes].join(', ')} } from './types'\n\n`
  }
  return out + body
}

// ---------------------------------------------------------------------------
// Command
// ---------------------------------------------------------------------------

export const apiSyncCommand = defineCommand({
  meta: {
    name: 'sync',
    description: 'Fetch the FastAPI OpenAPI spec and generate a typed client in frontend/src/openapi/.',
  },
  args: {
    root: {
      type: 'positional',
      description: 'Project root (defaults to current directory).',
      required: false,
    },
    url: {
      type: 'string',
      description: 'FastAPI base URL.',
      default: 'http://localhost:8000',
    },
    out: {
      type: 'string',
      description: 'Output directory relative to root.',
      default: 'frontend/src/openapi',
    },
  },
  async run({ args }) {
    const root = path.resolve(args.root ?? process.cwd())
    const outDir = path.join(root, args.out)
    const utilsDir = path.join(outDir, 'utils')
    const specUrl = `${args.url.replace(/\/$/, '')}/openapi.json`

    // -----------------------------------------------------------------------
    // 1. Fetch spec
    // -----------------------------------------------------------------------
    process.stdout.write(`Fetching spec from ${specUrl}…\n`)
    let spec: OpenAPI3
    try {
      const res = await fetch(specUrl)
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      spec = (await res.json()) as OpenAPI3
    } catch (err) {
      process.stderr.write(`error: could not fetch OpenAPI spec — ${(err as Error).message}\n`)
      process.stderr.write(`Make sure the FastAPI server is running at ${args.url}\n`)
      process.exit(1)
    }

    // -----------------------------------------------------------------------
    // 2. Save openapi.yaml
    // -----------------------------------------------------------------------
    mkdirSync(utilsDir, { recursive: true })
    const yamlPath = path.join(utilsDir, 'openapi.yaml')
    writeFileSync(yamlPath, yaml.stringify(spec), 'utf8')
    process.stdout.write(`Saved  ${path.relative(root, yamlPath)}\n`)

    // -----------------------------------------------------------------------
    // 3. Generate openapi.types.ts (full type surface via openapi-typescript)
    // -----------------------------------------------------------------------
    const typesPath = path.join(utilsDir, 'openapi.types.ts')
    if (shouldWrite(typesPath)) {
      const ast = await openapiTS(new URL(specUrl))
      writeFileSync(typesPath, astToString(ast), 'utf8')
      process.stdout.write(`Saved  ${path.relative(root, typesPath)}\n`)
    } else {
      process.stdout.write(`Skipped (no-override) ${path.relative(root, typesPath)}\n`)
    }

    // -----------------------------------------------------------------------
    // 4. Generate per-route types.ts + index.ts
    // -----------------------------------------------------------------------
    const paths_ = (spec as any).paths ?? {}
    let written = 0
    let skipped = 0

    for (const [route, methods] of Object.entries(paths_) as [string, Methods][]) {
      const segments = routeToSegments(route)
      const folderPath = path.join(outDir, ...segments)
      mkdirSync(folderPath, { recursive: true })

      const depth = segments.length + 1 // +1 for utils/ sibling at root of outDir

      const typesFile = path.join(folderPath, 'types.ts')
      if (safeWrite(typesFile, generateTypesFile(route, methods, depth))) {
        process.stdout.write(`Saved  ${path.relative(root, typesFile)}\n`)
        written++
      } else {
        process.stdout.write(`Skipped (no-override) ${path.relative(root, typesFile)}\n`)
        skipped++
      }

      const indexFile = path.join(folderPath, 'index.ts')
      if (safeWrite(indexFile, generateIndexFile(route, methods))) {
        process.stdout.write(`Saved  ${path.relative(root, indexFile)}\n`)
        written++
      } else {
        process.stdout.write(`Skipped (no-override) ${path.relative(root, indexFile)}\n`)
        skipped++
      }
    }

    process.stdout.write(`\n${written} file(s) written, ${skipped} skipped (no-override).\n`)
  },
})
