import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import path from 'pathe'
import yaml from 'yaml'
import openapiTS, { astToString } from 'openapi-typescript'
import type { OpenAPI3 } from 'openapi-typescript'
import type { StackCommandDef } from '@cubocicloide/dude'

// ---------------------------------------------------------------------------
// Shared constants & helpers
// ---------------------------------------------------------------------------

const NO_OVERRIDE = '// openapi-no-override'

const banner = `\
// This file is auto-generated by \`dude api sync\`.
// Manual changes will be overwritten on the next run.
// To keep your edits, add \`// openapi-no-override\` as the very first line.
`

function shouldWrite(filePath: string): boolean {
  if (!existsSync(filePath)) return true
  return !(readFileSync(filePath, 'utf8').split('\n')[0] ?? '').startsWith(NO_OVERRIDE)
}

function safeWrite(filePath: string, content: string): boolean {
  if (!shouldWrite(filePath)) return false
  mkdirSync(path.dirname(filePath), { recursive: true })
  writeFileSync(filePath, content, 'utf8')
  return true
}

function routeToSegments(route: string): string[] {
  return route
    .split('/')
    .filter(Boolean)
    .map((s) => s.replace(/{(.+?)}/g, '[$1]'))
}

function cap(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function toUtils(depth: number) {
  return '../'.repeat(depth) + 'utils/openapi.types'
}

function walkAll(dir: string): string[] {
  const results: string[] = []
  if (!existsSync(dir)) return results
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      results.push(full, ...walkAll(full))
    } else {
      results.push(full)
    }
  }
  return results
}

// ---------------------------------------------------------------------------
// Code generators (sync)
// ---------------------------------------------------------------------------

type Methods = Record<string, any>

function generateTypesFile(route: string, methods: Methods, depth: number): string {
  const imports = new Set<string>()
  let body = ''

  for (const [method, details] of Object.entries(methods)) {
    const M = cap(method)
    body += `// ${method.toUpperCase()}\n`

    if (details.parameters?.some((p: any) => p.in === 'query')) {
      imports.add('paths')
      body += `export type ${M}Parameters = paths['${route}']['${method}']['parameters']['query']\n`
    }

    if (details.requestBody?.content) {
      const content = details.requestBody.content
      const schema =
        content['application/json']?.schema ??
        content['multipart/form-data']?.schema ??
        content['application/x-www-form-urlencoded']?.schema
      if (schema?.$ref) {
        const name = (schema.$ref as string).split('/').pop()
        imports.add('components')
        body += `export type ${M}RequestBody = components['schemas']['${name}']\n`
      } else {
        body += `export type ${M}RequestBody = unknown\n`
      }
    }

    const firstCode = details.responses ? Object.keys(details.responses)[0] : undefined
    const responseContent = firstCode ? details.responses[firstCode]?.content : undefined
    if (responseContent) {
      const schema = responseContent['application/json']?.schema
      if (schema?.$ref) {
        const name = (schema.$ref as string).split('/').pop()
        imports.add('components')
        body += `export type ${M}Response = components['schemas']['${name}']\n`
      } else if (schema?.type === 'array' && schema.items?.$ref) {
        const name = (schema.items.$ref as string).split('/').pop()
        imports.add('components')
        body += `export type ${M}Response = components['schemas']['${name}'][]\n`
      } else {
        body += `export type ${M}Response = unknown\n`
      }
    } else {
      body += `export type ${M}Response = void\n`
    }

    body += '\n'
  }

  let out = banner
  if (imports.size > 0) {
    out += `import type { ${[...imports].join(', ')} } from '${toUtils(depth)}'\n\n`
  }
  return out + body
}

function generateIndexFile(route: string, methods: Methods): string {
  const pathParams = (route.match(/{(.+?)}/g) ?? []).map((m) => m.slice(1, -1))
  const importedTypes = new Set<string>()
  let body = ''

  for (const [method, details] of Object.entries(methods)) {
    const M = cap(method)
    const args: string[] = []

    if (pathParams.length > 0) args.push(pathParams.map((p) => `${p}: string`).join(', '))

    const hasQuery = details.parameters?.some((p: any) => p.in === 'query') ?? false
    const hasBody = !!details.requestBody

    if (hasQuery) {
      args.push(`params: ${M}Parameters`)
      importedTypes.add(`${M}Parameters`)
    }
    if (hasBody) {
      args.push(`body: ${M}RequestBody`)
      importedTypes.add(`${M}RequestBody`)
    }
    importedTypes.add(`${M}Response`)

    const urlExpr =
      pathParams.length > 0
        ? `\`${route.replace(/{(.+?)}/g, (_, p) => `\${${p}}`)}\``
        : `'${route}'`

    const fetchOpts: string[] = []
    if (method !== 'get') fetchOpts.push(`method: '${method.toUpperCase()}'`)
    if (hasBody) {
      fetchOpts.push(`headers: { 'Content-Type': 'application/json' }`)
      fetchOpts.push(`body: JSON.stringify(body)`)
    }
    const optsStr = fetchOpts.length > 0 ? `, { ${fetchOpts.join(', ')} }` : ''
    const urlStr = hasQuery
      ? `uri + '?' + new URLSearchParams(params as Record<string, string>)`
      : `uri`

    body += `export const $${method} = (${args.join(', ')}): Promise<${M}Response> => {\n`
    body += `  const uri = ${urlExpr}\n`
    body += `  return fetch(${urlStr}${optsStr}).then(r => r.json() as Promise<${M}Response>)\n`
    body += `}\n\n`
  }

  let out = banner
  if (importedTypes.size > 0) {
    out += `import type { ${[...importedTypes].join(', ')} } from './types'\n\n`
  }
  return out + body
}

// ---------------------------------------------------------------------------
// Core generation — callable from scaffold() without a live backend
// ---------------------------------------------------------------------------

/**
 * Generate the typed API client files from an OpenAPI spec object.
 * Used both by `dude api sync` (after fetching a live spec) and by
 * `scaffold()` (from the bundled openapi.yaml shipped in the template).
 */
export async function generateClientFromSpec(
  spec: OpenAPI3,
  outDir: string,
  root: string,
  log?: (msg: string) => void,
): Promise<{ written: number; skipped: number }> {
  mkdirSync(path.join(outDir, 'utils'), { recursive: true })

  // utils/openapi.types.ts — full TypeScript types from the spec
  const typesPath = path.join(outDir, 'utils', 'openapi.types.ts')
  if (shouldWrite(typesPath)) {
    const ast = await openapiTS(spec)
    writeFileSync(typesPath, astToString(ast), 'utf8')
    log?.(`Saved  ${path.relative(root, typesPath)}\n`)
  } else {
    log?.(`Skipped (no-override) ${path.relative(root, typesPath)}\n`)
  }

  // api/<route>/types.ts + api/<route>/index.ts — per-route files
  const specPaths = (spec as any).paths ?? {}
  let written = 0
  let skipped = 0

  for (const [route, methods] of Object.entries(specPaths) as [string, Methods][]) {
    const segments = routeToSegments(route)
    const folderPath = path.join(outDir, ...segments)
    mkdirSync(folderPath, { recursive: true })
    const depth = segments.length

    const typesFile = path.join(folderPath, 'types.ts')
    if (safeWrite(typesFile, generateTypesFile(route, methods, depth))) {
      log?.(`Saved  ${path.relative(root, typesFile)}\n`)
      written++
    } else {
      log?.(`Skipped (no-override) ${path.relative(root, typesFile)}\n`)
      skipped++
    }

    const indexFile = path.join(folderPath, 'index.ts')
    if (safeWrite(indexFile, generateIndexFile(route, methods))) {
      log?.(`Saved  ${path.relative(root, indexFile)}\n`)
      written++
    } else {
      log?.(`Skipped (no-override) ${path.relative(root, indexFile)}\n`)
      skipped++
    }
  }

  return { written, skipped }
}

// ---------------------------------------------------------------------------
// sync command
// ---------------------------------------------------------------------------

export const syncCommand: StackCommandDef = {
  description:
    'Fetch the FastAPI OpenAPI spec and generate a typed client in frontend/src/openapi/.',
  args: {
    url: { type: 'string', description: 'FastAPI base URL.', default: 'http://localhost:8000' },
    out: {
      type: 'string',
      description: 'Output directory relative to root.',
      default: 'frontend/src/openapi',
    },
  },
  async run({ projectRoot: root, args }) {
    const url = (args.url as string | undefined) ?? 'http://localhost:8000'
    const out = (args.out as string | undefined) ?? 'frontend/src/openapi'
    const outDir = path.join(root, out)
    const utilsDir = path.join(outDir, 'utils')
    const specUrl = `${url.replace(/\/$/, '')}/openapi.json`

    process.stdout.write(`Fetching spec from ${specUrl}…\n`)
    let spec: OpenAPI3
    try {
      const res = await fetch(specUrl)
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      spec = (await res.json()) as OpenAPI3
    } catch (err) {
      process.stderr.write(`error: could not fetch OpenAPI spec — ${(err as Error).message}\n`)
      process.stderr.write(`Make sure the FastAPI server is running at ${url}\n`)
      process.exit(1)
    }

    mkdirSync(utilsDir, { recursive: true })
    const yamlPath = path.join(utilsDir, 'openapi.yaml')
    writeFileSync(yamlPath, yaml.stringify(spec), 'utf8')
    process.stdout.write(`Saved  ${path.relative(root, yamlPath)}\n`)

    const { written, skipped } = await generateClientFromSpec(
      spec,
      outDir,
      root,
      (msg) => process.stdout.write(msg),
    )

    process.stdout.write(`\n${written} file(s) written, ${skipped} skipped (no-override).\n`)
  },
}

// ---------------------------------------------------------------------------
// review command
// ---------------------------------------------------------------------------

export const reviewCommand: StackCommandDef = {
  description: 'Validate the frontend/src/openapi/ tree against the saved OpenAPI spec.',
  args: {
    out: {
      type: 'string',
      description: 'Generated openapi directory relative to root.',
      default: 'frontend/src/openapi',
    },
  },
  async run({ projectRoot: root, args }) {
    const out = (args.out as string | undefined) ?? 'frontend/src/openapi'
    const outDir = path.join(root, out)
    const yamlPath = path.join(outDir, 'utils', 'openapi.yaml')
    const isTTY = process.stdout.isTTY

    if (!existsSync(yamlPath)) {
      process.stderr.write(
        `error: ${path.relative(root, yamlPath)} not found.\n` +
          `Run \`dude api sync\` first to fetch the spec.\n`,
      )
      process.exit(1)
    }

    const spec = yaml.parse(readFileSync(yamlPath, 'utf8')) as { paths?: Record<string, unknown> }
    const specPaths = spec.paths ?? {}
    const expectedFolders = new Set<string>()
    const expectedFiles = new Set<string>()

    for (const route of Object.keys(specPaths)) {
      const segments = routeToSegments(route)
      for (let i = 1; i <= segments.length; i++) {
        expectedFolders.add(path.join(outDir, ...segments.slice(0, i)))
      }
      const leafDir = path.join(outDir, ...segments)
      expectedFiles.add(path.join(leafDir, 'types.ts'))
      expectedFiles.add(path.join(leafDir, 'index.ts'))
    }

    const utilsDir = path.join(outDir, 'utils')
    expectedFolders.add(utilsDir)
    expectedFiles.add(path.join(utilsDir, 'openapi.yaml'))
    expectedFiles.add(path.join(utilsDir, 'openapi.types.ts'))

    const actual = walkAll(outDir)
    const issues: Array<{ kind: 'unexpected' | 'missing'; item: string }> = []

    for (const item of actual) {
      const isDir = statSync(item).isDirectory()
      if (isDir) {
        if (!expectedFolders.has(item) && item !== outDir) issues.push({ kind: 'unexpected', item })
      } else {
        if (!expectedFiles.has(item)) issues.push({ kind: 'unexpected', item })
      }
    }
    for (const f of [...expectedFolders, ...expectedFiles]) {
      if (!existsSync(f)) issues.push({ kind: 'missing', item: f })
    }

    if (issues.length === 0) {
      process.stdout.write('No issues found.\n')
      return
    }

    const colorize = (s: string, kind: 'unexpected' | 'missing') =>
      isTTY ? (kind === 'unexpected' ? `\x1b[31m${s}\x1b[0m` : `\x1b[33m${s}\x1b[0m`) : s

    let errors = 0
    let warnings = 0
    for (const { kind, item } of issues) {
      const rel = path.relative(root, item)
      if (kind === 'unexpected') {
        process.stdout.write(
          colorize(`${rel}: error: unexpected file/folder (not in OpenAPI spec)`, kind) + '\n',
        )
        errors++
      } else {
        process.stdout.write(
          colorize(
            `${rel}: warning: expected by spec but not found — run \`dude api sync\``,
            kind,
          ) + '\n',
        )
        warnings++
      }
    }

    const summary = [
      errors > 0 ? `${errors} error${errors > 1 ? 's' : ''}` : '',
      warnings > 0 ? `${warnings} warning${warnings > 1 ? 's' : ''}` : '',
    ]
      .filter(Boolean)
      .join(', ')
    process.stderr.write(`\n${summary}\n`)
    process.exit(errors > 0 ? 1 : 0)
  },
}
