from drf_spectacular.utils import extend_schema
from rest_framework.mixins import CreateModelMixin, ListModelMixin, RetrieveModelMixin
from rest_framework.parsers import MultiPartParser
from rest_framework.permissions import AllowAny
from rest_framework.viewsets import GenericViewSet

from apps.files.models import FileUpload
from apps.files.serializers import FileUploadSerializer


@extend_schema(tags=["files"])
class FileUploadViewSet(CreateModelMixin, ListModelMixin, RetrieveModelMixin, GenericViewSet):
    """Upload (multipart), list and retrieve stored files.

    Writes go through ``apps.files.services`` via the serializer (lint rule
    BE005); downloads use presigned URLs generated by the storage backend.
    """

    queryset = FileUpload.objects.all()
    serializer_class = FileUploadSerializer
    parser_classes = [MultiPartParser]
    # Demo endpoint: AllowAny so the scaffold works out of the box. Tighten to
    # IsAuthenticated before exposing real data — but keep the declaration
    # explicit: every view must declare permission_classes (lint rule BE003).
    permission_classes = [AllowAny]

    @extend_schema(operation_id="files_create", description="Upload a file (multipart/form-data).")
    def create(self, request, *args, **kwargs):
        return super().create(request, *args, **kwargs)
