#!/usr/bin/env node
/**
 * Compose the root documentation site from per-stack sources.
 *
 * Each stack is the single source of truth for its own facts: its
 * `StackDefinition` (name, version, minDudeVersion, description, variables) and
 * its optional `docs` manifest (tagline, use cases, technologies, IaC target,
 * page set). This script harvests those, plus what can be derived from the tree
 * (lint check groups, `.claude/rules` counts), and generates:
 *
 *   docs/docs/stacks/index.md   — stack index + the cross-stack comparison matrix
 *   docs/docs/stacks/<id>.md    — one page per stack
 *   docs/mkdocs.yml             — the `nav:` entries between the composed markers
 *
 * Generated output is COMMITTED, so `.github/workflows/docs.yml` stays a pure
 * `mkdocs build` over committed files — no Node dependency in the Pages
 * workflow, and its `paths: docs/**` filter keeps working. The anti-drift gate
 * lives in `ci.yml` instead, which already builds every package:
 *
 *   make docs-data    regenerate
 *   make docs-check   regenerate + fail if the committed output differs
 *
 * Plain ESM JavaScript rather than TypeScript on purpose: it keeps `make
 * docs-check` runnable with bare `node`, with no root-level TS runner to install
 * and no lockfile churn. It consumes a zod-validated manifest, so the data it
 * reads is already checked at the boundary.
 *
 * Run it via `make docs-data` (which builds first — the stack definitions are
 * imported from each stack's compiled `dist/index.js`).
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DOCS = path.join(REPO, 'docs', 'docs')
const STACKS_OUT = path.join(DOCS, 'stacks')
const MKDOCS_YML = path.join(REPO, 'docs', 'mkdocs.yml')

const NAV_START = '  # <!-- composed:stacks:start — generated by `make docs-data`, do not edit -->'
const NAV_END = '  # <!-- composed:stacks:end -->'

const banner = (self) =>
  `<!-- GENERATED FILE — do not edit.\n` +
  `     Produced by scripts/compose-docs.mjs from each stack's \`docs\` manifest.\n` +
  `     Change the manifest in stacks/<id>/src/index.ts, then run \`make docs-data\`.\n` +
  `     ${self} -->\n`

// ── Harvest ───────────────────────────────────────────────────────────────────

function loadRegistry() {
  const file = path.join(REPO, 'packages', 'dude', 'registry.json')
  const { stacks } = JSON.parse(readFileSync(file, 'utf8'))
  // Alphabetical, so the generated output is stable regardless of registry order.
  return Object.keys(stacks)
    .sort()
    .map((id) => ({ id, ...stacks[id] }))
}

async function loadDefinition(id) {
  const dist = path.join(REPO, 'stacks', id, 'dist', 'index.js')
  if (!existsSync(dist)) {
    throw new Error(
      `Stack "${id}" has not been built: ${path.relative(REPO, dist)} is missing.\n` +
        `The composer imports each stack's compiled definition. Run:\n\n` +
        `  make build              # build every package\n` +
        `  pnpm --filter @cubocicloide/stack-${id} build   # or just this stack\n`,
    )
  }
  const mod = await import(pathToFileURL(dist).href)
  if (!mod.default?.name) throw new Error(`Stack "${id}" does not default-export a definition.`)
  return mod.default
}

/** Lint check groups and their counts, derived from the source tree. */
function harvestLintGroups(id) {
  const root = path.join(REPO, 'stacks', id, 'src', 'commands', 'lint', 'checks')
  if (!existsSync(root)) return {}
  const groups = {}
  for (const group of readdirSync(root, { withFileTypes: true })) {
    if (!group.isDirectory()) continue
    const checks = readdirSync(path.join(root, group.name)).filter(
      (f) => /\.(ts|js)$/.test(f) && !f.endsWith('.test.ts') && !f.endsWith('.test.js'),
    )
    if (checks.length) groups[group.name] = checks.length
  }
  return groups
}

/** Prose rule files shipped in the stack's template, keyed by group. */
function harvestRuleFiles(id) {
  const root = path.join(REPO, 'stacks', id, 'templates', 'base', '.claude', 'rules')
  if (!existsSync(root)) return {}
  const groups = {}
  for (const group of readdirSync(root, { withFileTypes: true })) {
    if (!group.isDirectory()) continue
    const rules = readdirSync(path.join(root, group.name)).filter((f) => f.endsWith('.md'))
    if (rules.length) groups[group.name] = rules.length
  }
  return groups
}

/**
 * Enforce the lint↔rule parity invariant (`.claude/rules/002`) mechanically.
 * Every stack check must ship a matching prose rule file, and vice versa. This
 * used to be a convention only; harvesting both sides here makes it checkable,
 * so `make docs-check` in CI now catches a check added without its rule file.
 */
function assertLintRuleParity(stacks) {
  const problems = []
  for (const s of stacks) {
    const groups = new Set([...Object.keys(s.lintGroups), ...Object.keys(s.ruleGroups)])
    for (const g of [...groups].sort()) {
      const checks = s.lintGroups[g] ?? 0
      const rules = s.ruleGroups[g] ?? 0
      if (checks !== rules) {
        problems.push(
          `  ${s.id} group ${g}: ${checks} check(s) but ${rules} rule file(s) — ` +
            `see .claude/rules/002-lint-template-parity.md`,
        )
      }
    }
  }
  if (problems.length) {
    throw new Error(
      `Lint↔rule parity is broken (every stack check needs a matching ` +
        `templates/base/.claude/rules/<GROUP>/NNN.md):\n\n${problems.join('\n')}\n`,
    )
  }
}

/**
 * `docs/docs/commands.md` stays HAND-WRITTEN: its value is the narrative a
 * generated flag dump cannot carry (why release channels exist, that you must run
 * `pnpm install` after `dude upgrade`, and so on). Generating it would trade that
 * prose for a table an agent gets better from `dude help --format json` anyway.
 *
 * What is checked mechanically is completeness: every core command in the live
 * catalog must have a `## \`dude <name>\`` heading on the page. So adding a core
 * command forces documenting it, without giving up the prose.
 */
async function assertCommandsPageComplete() {
  const page = path.join(DOCS, 'commands.md')
  const { generateApiDoc } = await import(
    pathToFileURL(path.join(REPO, 'packages', 'dude', 'dist', 'index.js')).href
  )
  // The repo root has no dude.json, so the catalog resolves to core-only —
  // exactly the scope of this page.
  const catalog = JSON.parse(await generateApiDoc(REPO, 'json'))
  const documented = readFileSync(page, 'utf8')
  const missing = catalog.commands
    .map((c) => c.name)
    .filter((name) => !documented.includes(`## \`dude ${name}\``))

  if (missing.length) {
    throw new Error(
      `docs/docs/commands.md does not document every core command.\n\n` +
        missing.map((n) => `  - missing a "## \`dude ${n}\`" section`).join('\n') +
        `\n\nThe page is hand-written on purpose (the narrative matters), but it must stay\n` +
        `complete — a command absent from it is invisible to anyone reading the site.\n`,
    )
  }
}

async function collect() {
  const stacks = []
  for (const entry of loadRegistry()) {
    const definition = await loadDefinition(entry.id)
    stacks.push({
      id: entry.id,
      package: entry.package,
      minimumSupported: entry.minimumSupported,
      definition,
      docs: definition.docs,
      lintGroups: harvestLintGroups(entry.id),
      ruleGroups: harvestRuleFiles(entry.id),
    })
  }
  assertLintRuleParity(stacks)
  return stacks
}

// ── Render helpers ────────────────────────────────────────────────────────────

/**
 * Escape a value for use inside a Markdown table cell.
 *
 * Backslashes must be escaped BEFORE pipes: escaping only the pipe leaves an
 * input ending in `\` producing `\\|`, where the backslash escapes itself and
 * the pipe becomes a live column separator again — splitting the row. (CodeQL's
 * js/incomplete-sanitization catches exactly this ordering mistake.)
 */
const cell = (s) => String(s).replace(/\\/g, '\\\\').replace(/\|/g, '\\|')

const totalChecks = (s) => Object.values(s.lintGroups).reduce((a, b) => a + b, 0)

const lintGroupLabel = (s) => {
  const names = Object.keys(s.lintGroups).sort()
  return names.length ? names.map((g) => `\`${g}\``).join(', ') : '—'
}

/**
 * The `dude init` flag for a declared variable. Boolean variables are bare
 * switches; everything else takes a value. Derived rather than hand-listed, so
 * a stack that adds a variable gets a correct row for free.
 *
 * Variable names are camelCase in the contract; the flag is rendered in
 * kebab-case because that is the conventional CLI form. `init`'s `normalizeKey`
 * lowercases and strips dashes, so `--celeryBeat`, `--celerybeat` and
 * `--celery-beat` are all the same flag — the pages say so.
 */
const flagName = (name) => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()

function variableFlag(v) {
  const flag = flagName(v.name)
  if (v.type === 'boolean') return `\`--${flag}\``
  if (v.type === 'select') return `\`--${flag} <${v.choices.map(cell).join('\\|')}>\``
  return `\`--${flag} <value>\``
}

function variableDefault(v) {
  if (v.default === undefined) return '—'
  return `\`${String(v.default)}\``
}

// ── Render: one page per stack ────────────────────────────────────────────────

function renderStackPage(s) {
  const d = s.definition
  const m = s.docs
  const out = [banner(`docs/docs/stacks/${s.id}.md`)]

  out.push(`# \`${s.id}\``, '')
  // The manifest tagline supersedes the terser contract `description`; fall back
  // to the description for a stack that has not adopted the manifest yet.
  out.push(m?.tagline ?? d.description, '')

  if (m?.technologies?.length) {
    out.push(`**Built with:** ${m.technologies.map((t) => `\`${t}\``).join(' · ')}`, '')
  }

  out.push('---', '', '## Scaffold it', '', '```bash', `dude init my-app --stack ${s.id}`, '```', '')

  if (d.variables?.length) {
    out.push(
      'The questions `dude init` asks for this stack — pass the matching flag to',
      'answer it non-interactively. Flag names ignore case and dashes, so',
      '`--celery-beat`, `--celeryBeat` and `--celerybeat` are the same flag.',
      '',
      '| Question | Flag | Default |',
      '| -------- | ---- | ------- |',
    )
    for (const v of d.variables) {
      const prompt = cell(v.prompt ?? v.name)
      out.push(`| ${prompt} | ${variableFlag(v)} | ${variableDefault(v)} |`)
    }
    out.push('')
  }

  if (m?.useCases?.length) {
    out.push('## What it is for', '')
    for (const u of m.useCases) out.push(`- ${u}`)
    out.push('')
  }

  if (m?.iac) {
    out.push(
      '## Deploying to the cloud',
      '',
      `This stack ships an infrastructure-as-code target: **${m.iac.provider}**.`,
      `Enable it at scaffold time with \`${m.iac.flag}\`, then use the \`dude iac\``,
      'command group inside the generated project. The full deploy guide is part of',
      'the project\'s own documentation — run `dude docs` after scaffolding.',
      '',
    )
  }

  const checks = totalChecks(s)
  if (checks) {
    out.push(
      '## Conventions it enforces',
      '',
      `\`dude lint\` runs **${checks} structural checks** for this stack, grouped by`,
      'area. Each one ships a prose rule file in the generated project under',
      '`.claude/rules/`, so both you and a coding agent can see why a check exists',
      'and how to fix a violation.',
      '',
      '| Group | Checks |',
      '| ----- | ------ |',
    )
    for (const g of Object.keys(s.lintGroups).sort()) {
      out.push(`| \`${g}\` | ${s.lintGroups[g]} |`)
    }
    out.push('')
  }

  if (m?.pages?.length) {
    out.push(
      '## Documentation inside the project',
      '',
      'Every scaffolded project gets its own documentation site, served with',
      '`dude docs`. This stack ships:',
      '',
      '| Page | Title | Included |',
      '| ---- | ----- | -------- |',
    )
    for (const p of m.pages) {
      const when = p.when ? `when \`${p.when}\`` : 'always'
      out.push(`| \`${cell(p.file)}\` | ${cell(p.title)} | ${when} |`)
    }
    out.push('')
  }

  // Deliberately NOT emitting the stack's current version: `changeset version`
  // rewrites it mechanically in the Release PR, which would leave this committed
  // page stale and break `make docs-check` on master after every release. The
  // published version belongs on npm, which is always authoritative.
  out.push(
    '## Versions',
    '',
    `- **Package:** [\`${s.package}\`](https://www.npmjs.com/package/${s.package})`,
    `- **Requires dude:** \`>= ${d.minDudeVersion}\``,
    '',
    'Both the CLI and the stack are pinned per project, so different projects can',
    'sit on different versions. See [How it works](../concepts.md).',
    '',
  )

  return out.join('\n')
}

// ── Render: the index + comparison matrix ─────────────────────────────────────

function renderIndex(stacks) {
  const out = [banner('docs/docs/stacks/index.md')]

  out.push(
    '# Stacks',
    '',
    'A **stack** is a versioned blueprint for a whole application: the templates to',
    'scaffold it, the lint rules that keep it consistent, and the commands to run and',
    'ship it. Pick one at `dude init` with `--stack <id>`.',
    '',
    '```bash',
    'dude init my-app --stack react-fastapi',
    '```',
    '',
    '---',
    '',
    '## Available stacks',
    '',
  )

  for (const s of stacks) {
    out.push(`### [\`${s.id}\`](${s.id}.md)`, '')
    if (s.docs?.tagline) out.push(s.docs.tagline, '')
    else out.push(s.definition.description, '')
  }

  out.push(
    '---',
    '',
    '## At a glance',
    '',
    '| Stack | Cloud target | Lint groups | Checks | Requires dude |',
    '| ----- | ------------ | ----------- | -----: | ------------- |',
  )
  for (const s of stacks) {
    const iac = s.docs?.iac ? `\`${s.docs.iac.provider}\`` : '—'
    out.push(
      `| [\`${s.id}\`](${s.id}.md) | ${iac} | ${lintGroupLabel(s)} | ` +
        `${totalChecks(s) || '—'} | \`>= ${s.definition.minDudeVersion}\` |`,
    )
  }
  out.push('')

  const withCases = stacks.filter((s) => s.docs?.useCases?.length)
  if (withCases.length) {
    out.push(
      '## Choosing a stack',
      '',
      "| If you're building… | Use |",
      '| ------------------- | --- |',
    )
    for (const s of withCases) {
      for (const u of s.docs.useCases) {
        out.push(`| ${cell(u)} | [\`${s.id}\`](${s.id}.md) |`)
      }
    }
    out.push('')
  }

  out.push(
    '---',
    '',
    '## What every stack gives you',
    '',
    'However different the technologies, the workflow is the same across stacks:',
    '',
    '- `dude up` / `dude down` — run the project locally in Docker.',
    "- `dude lint` — enforce the stack's structural conventions.",
    "- `dude test` — run the project's test suites.",
    "- `dude docs` — serve the project's own documentation site.",
    '- Optional `dude iac …` — provision and ship to the cloud, when the stack',
    '  supports it and you enabled IaC at init.',
    '',
    'The exact command set is always discoverable with `dude help` inside the',
    'project — it reflects your init answers and any project-local commands.',
    '',
  )

  return out.join('\n')
}

// ── Render: the machine-readable surface (issue #117) ────────────────────────

/**
 * Per-stack JSON, for tooling and coding agents that need to pick or drive a
 * stack without parsing prose.
 *
 * `variables` is the authoritative answer to "what flags does `dude init` take
 * for this stack" — the same data the CLI prompts from, with the kebab-case flag
 * spelled out so nothing has to be inferred. `schema` is versioned because
 * something depending on this shape should not break silently on the next
 * release.
 *
 * Deliberately no `version` field: `changeset version` rewrites package versions
 * in the Release PR, which would leave this committed file stale and break
 * `make docs-check` on master after every release. npm is authoritative for that.
 */
function renderStackJson(s) {
  const d = s.definition
  return (
    JSON.stringify(
      {
        schema: 'dude.stack/1',
        id: s.id,
        package: s.package,
        description: d.description,
        tagline: s.docs?.tagline ?? null,
        technologies: s.docs?.technologies ?? [],
        useCases: s.docs?.useCases ?? [],
        requiresDude: d.minDudeVersion,
        iac: s.docs?.iac ?? null,
        init: {
          command: `dude init my-app --stack ${s.id}`,
          variables: (d.variables ?? []).map((v) => ({
            name: v.name,
            flag: `--${flagName(v.name)}`,
            type: v.type,
            prompt: v.prompt ?? null,
            default: v.default ?? null,
            choices: v.type === 'select' ? v.choices : null,
          })),
          // Flag names are matched case- and dash-insensitively by `dude init`.
          flagsAreCaseAndDashInsensitive: true,
        },
        lint: {
          groups: Object.keys(s.lintGroups)
            .sort()
            .map((g) => ({ group: g, checks: s.lintGroups[g] })),
          totalChecks: totalChecks(s),
          // Each check ships prose at this path inside the generated project.
          rulePathTemplate: '.claude/rules/<GROUP>/<NNN>.md',
        },
        docsPages: s.docs?.pages ?? [],
        // Inside a scaffolded project this is the one call that returns the live,
        // answer-filtered command catalog plus every lint rule.
        cheatsheet: 'dude cheatsheet --format json',
      },
      null,
      2,
    ) + '\n'
  )
}

/**
 * `llms.txt` — the convention for telling a model what a site contains and where
 * to look, without crawling it. Kept to stable URLs and one line of intent each.
 */
function renderLlmsTxt(stacks) {
  const out = [
    '# dude',
    '',
    "> Cubocicloide's project scaffolding and code-quality CLI. You pick a stack; dude",
    '> scaffolds the project, then enforces its structural conventions mechanically',
    '> with `dude lint` — so an agent working in a dude project can verify its own',
    '> output instead of guessing the conventions.',
    '',
    'This file is generated by `make docs-data`. Machine-readable entry points first.',
    '',
    '## Start here (machine-readable)',
    '',
    '- [Stack index](/stacks/): every stack, with a comparison matrix.',
    ...stacks.map((s) => `- [${s.id} (JSON)](/stacks/${s.id}.json): ${s.docs?.tagline ?? s.definition.description}`),
    '',
    '## Inside a scaffolded project',
    '',
    'Two commands answer almost everything, and both take `--format json`:',
    '',
    '- `dude cheatsheet --format json` — the project’s live command catalog, every',
    '  lint rule with its code and title, the verify loop, and the init answers.',
    '  One call; prefer it over reading the site.',
    '- `dude help --format json` — the merged command catalog on its own (core +',
    '  active stack + project-local commands under `.dude/commands/`).',
    '',
    'Each lint rule has prose at `.claude/rules/<GROUP>/<NNN>.md` in the project,',
    'explaining why it exists and how to fix a violation. Read that before working',
    'around a diagnostic.',
    '',
    '## Prose documentation',
    '',
    '- [Home](/): what dude is and who it is for.',
    '- [Getting started](/getting-started/): install and scaffold a first project.',
    '- [How it works](/concepts/): the launcher, pinned toolchains, stack plugins,',
    '  template overlays, release channels.',
    '- [Command reference](/commands/): the core, stack-agnostic commands.',
    '- [Troubleshooting](/troubleshooting/): common issues and how to file a report.',
    '',
    '## Per-stack pages',
    '',
    ...stacks.map((s) => `- [${s.id}](/stacks/${s.id}/): scaffold flags, enforced conventions, page set.`),
    '',
  ]
  return out.join('\n')
}

// ── Render: the mkdocs nav section ───────────────────────────────────────────

function updateMkdocsNav(stacks) {
  const yml = readFileSync(MKDOCS_YML, 'utf8')
  const start = yml.indexOf(NAV_START)
  const end = yml.indexOf(NAV_END)
  if (start === -1 || end === -1) {
    throw new Error(
      `Could not find the composed nav markers in docs/mkdocs.yml.\n` +
        `Expected these two lines to be present:\n\n${NAV_START}\n${NAV_END}\n`,
    )
  }
  const section = [
    NAV_START,
    '  - Stacks:',
    '      - Overview: stacks/index.md',
    ...stacks.map((s) => `      - ${s.id}: stacks/${s.id}.md`),
    NAV_END,
  ].join('\n')

  const next = yml.slice(0, start) + section + yml.slice(end + NAV_END.length)
  if (next !== yml) writeFileSync(MKDOCS_YML, next)
}

// ── Main ─────────────────────────────────────────────────────────────────────

const stacks = await collect()
await assertCommandsPageComplete()

// Wipe and rewrite, so a removed stack's page does not linger.
rmSync(STACKS_OUT, { recursive: true, force: true })
mkdirSync(STACKS_OUT, { recursive: true })

writeFileSync(path.join(STACKS_OUT, 'index.md'), renderIndex(stacks))
for (const s of stacks) {
  writeFileSync(path.join(STACKS_OUT, `${s.id}.md`), renderStackPage(s))
  writeFileSync(path.join(STACKS_OUT, `${s.id}.json`), renderStackJson(s))
}
writeFileSync(path.join(DOCS, 'llms.txt'), renderLlmsTxt(stacks))
updateMkdocsNav(stacks)

process.stdout.write(
  `[compose-docs] Generated ${stacks.length + 1} pages + ${stacks.length} JSON files ` +
    `under docs/docs/stacks/ (${stacks.map((s) => s.id).join(', ')}), llms.txt, ` +
    `and refreshed the mkdocs nav.\n`,
)
