// This file is auto-generated by `dude api sync`.
// Manual changes will be overwritten on the next run.
// To keep your edits, add `// openapi-no-override` as the very first line.

// Minimal types generated from the default FastAPI spec.
// Re-run `dude api sync` after adding or changing backend routes.

export type paths = {
  '/api/health': {
    get: {
      parameters: Record<string, never>
      responses: {
        200: {
          content: {
            'application/json': Record<string, string>
          }
        }
      }
    }
  }
}

export type components = {
  schemas: Record<string, never>
}
