// This file is auto-generated by `dude api sync`.
// Manual changes will be overwritten on the next run.
// To keep your edits, add `// openapi-no-override` as the very first line.

import type { GetResponse } from './types'

export const $get = (): Promise<GetResponse> => {
  const uri = '/api/health'
  return fetch(uri).then((r) => r.json() as Promise<GetResponse>)
}
