// This file is auto-generated by `dude api sync`.
// Manual changes will be overwritten on the next run.
// To keep your edits, add `// openapi-no-override` as the very first line.

export type GetResponse = Record<string, string>
